
import React from 'react';
// Fix: Moved Rarity from type-only import to value import to allow its use as a value.
import type { FliffyColor, FliffyPattern, HuntingLocation, Upgrade, RebirthUpgrade } from './types';
import { Rarity, UpgradeType, RebirthUpgradeType } from './types';

export const RARITY_DATA: Record<Rarity, { color: string; multiplier: number }> = {
  [Rarity.Common]: { color: 'text-gray-500', multiplier: 1 },
  [Rarity.Uncommon]: { color: 'text-green-500', multiplier: 2.5 },
  [Rarity.Rare]: { color: 'text-blue-500', multiplier: 10 },
  [Rarity.Epic]: { color: 'text-purple-600', multiplier: 50 },
  [Rarity.Legendary]: { color: 'text-amber-500', multiplier: 250 },
};

export const FLIFFY_COLORS: FliffyColor[] = [
  { name: 'Snow', hex: '#FFFFFF', rarity: Rarity.Common },
  { name: 'Ash', hex: '#A0A0A0', rarity: Rarity.Common },
  { name: 'Sky', hex: '#87CEEB', rarity: Rarity.Uncommon },
  { name: 'Mint', hex: '#98FF98', rarity: Rarity.Uncommon },
  { name: 'Rose', hex: '#FFC0CB', rarity: Rarity.Rare },
  { name: 'Lavender', hex: '#E6E6FA', rarity: Rarity.Rare },
  { name: 'Crimson', hex: '#DC143C', rarity: Rarity.Epic },
  { name: 'Amethyst', hex: '#9966CC', rarity: Rarity.Epic },
  { name: 'Goldenrod', hex: '#DAA520', rarity: Rarity.Legendary },
  { name: 'Obsidian', hex: '#343434', rarity: Rarity.Legendary },
];

export const FLIFFY_PATTERNS: FliffyPattern[] = [
  { name: 'Solid', id: 'solid', rarity: Rarity.Common },
  { name: 'Spotted', id: 'spotted', rarity: Rarity.Uncommon },
  { name: 'Striped', id: 'striped', rarity: Rarity.Rare },
  { name: 'Swirl', id: 'swirl', rarity: Rarity.Epic },
  { name: 'Stardust', id: 'stardust', rarity: Rarity.Legendary },
];

export const HUNTING_LOCATIONS: HuntingLocation[] = [
    {
        id: 'meadow',
        name: 'Sunny Meadow',
        cost: 0,
        rarityChances: {
            [Rarity.Common]: 0.75,
            [Rarity.Uncommon]: 0.20,
            [Rarity.Rare]: 0.05,
            [Rarity.Epic]: 0,
            [Rarity.Legendary]: 0,
        },
        icon: <LeafIcon />,
    },
    {
        id: 'forest',
        name: 'Whispering Forest',
        cost: 1000,
        rarityChances: {
            [Rarity.Common]: 0.40,
            [Rarity.Uncommon]: 0.45,
            [Rarity.Rare]: 0.14,
            [Rarity.Epic]: 0.01,
            [Rarity.Legendary]: 0,
        },
        icon: <TreeIcon />,
    },
    {
        id: 'caves',
        name: 'Crystal Caves',
        cost: 50000,
        rarityChances: {
            [Rarity.Common]: 0.10,
            [Rarity.Uncommon]: 0.40,
            [Rarity.Rare]: 0.40,
            [Rarity.Epic]: 0.09,
            [Rarity.Legendary]: 0.01,
        },
        icon: <DiamondIcon />,
    },
    {
        id: 'volcano',
        name: 'Volcanic Peak',
        cost: 1000000,
        rarityChances: {
            [Rarity.Common]: 0.0,
            [Rarity.Uncommon]: 0.20,
            [Rarity.Rare]: 0.50,
            [Rarity.Epic]: 0.25,
            [Rarity.Legendary]: 0.05,
        },
        icon: <FlameIcon />,
    },
];

export const UPGRADES_DATA: Upgrade[] = [
  { id: UpgradeType.IncomeMultiplier, name: 'Fliffy Motivation', description: 'Boosts Fliff Bucks generated by all Fliffys by 10% per level.', baseCost: 100, level: 0, maxLevel: 50, costMultiplier: 1.5 },
  { id: UpgradeType.HuntCostReduction, name: 'Expert Hunter', description: 'Reduces the cost of hunting in all locations by 5% per level.', baseCost: 500, level: 0, maxLevel: 10, costMultiplier: 2.5 },
  { id: UpgradeType.RareFliffyChance, name: 'Lucky Charm', description: 'Slightly increases the chance of finding rarer Fliffys.', baseCost: 2000, level: 0, maxLevel: 20, costMultiplier: 3 },
];

export const REBIRTH_UPGRADES_DATA: RebirthUpgrade[] = [
  { id: RebirthUpgradeType.PermanentIncomeBoost, name: 'Eternal Fluffiness', description: 'Permanently boosts all Fliff Buck generation by 25% per level.', baseCost: 1, level: 0, maxLevel: 100, costMultiplier: 2 },
  { id: RebirthUpgradeType.StartingFliffBucks, name: 'Head Start', description: 'Start each new life with more Fliff Bucks.', baseCost: 5, level: 0, maxLevel: 20, costMultiplier: 3 },
  { id: RebirthUpgradeType.FluffPointGain, name: 'Soul Magnifier', description: 'Earn more Fluff Points when you rebirth.', baseCost: 10, level: 0, maxLevel: 30, costMultiplier: 4 },
];

// ICONS
function LeafIcon() {
    return <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>;
}
function TreeIcon() {
    return <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 21v-4m0 0V5a2 2 0 012-2h6.5l1 1H21l-3 6 3 6h-8.5l-1-1H5a2 2 0 00-2 2zm9-13.5V9" /></svg>;
}
function DiamondIcon() {
    return <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v.01M12 6a2 2 0 100-4 2 2 0 000 4zm0 12a2 2 0 100-4 2 2 0 000 4z" /></svg>;
}
function FlameIcon() {
    return <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17.657 18.657A8 8 0 016.343 7.343S7 9 9 10c0-2 .5-5 2.986-7.014A8.003 8.003 0 0112 2a8.003 8.003 0 015.014 1.986C19.5 5 20 8 20 10c2 1 2.657 2.343 2.657 2.657a8 8 0 01-5.001 6.001z" /></svg>;
}
